include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    non_constant_identifier_names: false
    depend_on_referenced_packages: false
    require_trailing_commas: false