name: ny_articles_clean_architecture
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  shimmer: ^3.0.0
  dio_smart_retry: ^6.0.0


dev_dependencies:
  bloc_test: ^9.1.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  very_good_analysis: ^5.1.0
  device_preview: ^1.1.0
  mocktail: ^1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
